{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "microservices.fullname" . }}-backend
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "microservices.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "microservices.fullname" . }}-frontend
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "microservices.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
---
{{- if and .Values.monitoring.enabled .Values.monitoring.otelCollector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservices.fullname" . }}-otel-config
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      resource:
        attributes:
        - key: service.name
          from_attribute: service_name
          action: insert
    exporters:
      otlp:
        endpoint: http://tempo-service:4317
        tls:
          insecure: true
      logging:
        loglevel: debug
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [otlp, logging]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices.fullname" . }}-otel-collector
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "microservices.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: otel-collector
  template:
    metadata:
      labels:
        {{- include "microservices.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: "{{ .Values.monitoring.otelCollector.image.repository }}:{{ .Values.monitoring.otelCollector.image.tag }}"
        args: ["--config=/etc/otel/otel-config.yaml"]
        ports:
        - containerPort: 4317
        - containerPort: 4318
        volumeMounts:
        - name: config
          mountPath: /etc/otel
        resources:
          {{- toYaml .Values.monitoring.otelCollector.resources | nindent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "microservices.fullname" . }}-otel-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-otel-collector
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  selector:
    {{- include "microservices.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317
  - name: http
    port: 4318
    targetPort: 4318
{{- end }}