global:
  imageRegistry: ""
  imagePullSecrets: []

frontend:
  enabled: true
  image:
    repository: monitoring/frontend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 3
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: frontend.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

backend:
  enabled: true
  image:
    repository: monitoring/backend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 3
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "production"
  livenessProbe:
    httpGet:
      path: /api/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /api/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5

mysql:
  enabled: true
  auth:
    rootPassword: "mysqlpassword"
    database: "monitoring"
  primary:
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 1Gi
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
  otelCollector:
    enabled: true
    image:
      repository: otel/opentelemetry-collector-contrib
      tag: latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  fluentBit:
    enabled: true
    image:
      repository: fluent/fluent-bit
      tag: "2.1"
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  exporters:
    mysql:
      enabled: true
      image:
        repository: prom/mysqld-exporter
        tag: latest
    redis:
      enabled: true
      image:
        repository: oliver006/redis_exporter
        tag: latest

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}