apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/monitoring-stack
    targetRevision: HEAD
    path: infra-code/gcp
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true