k8s-monitoring:
  cluster:
    name: devops-cluster
  externalServices:
    prometheus:
      host: 'https://mimir.example.com'
      tenantId: _devops
      authMode: basic
      basicAuth:
        username: observe
        password: ${MIMIR_PASSWORD}
    loki:
      host: 'https://loki.example.com'
      tenantId: _devops
      authMode: basic
      basicAuth:
        username: observe
        password: ${LOKI_PASSWORD}
    tempo:
      host: 'tempo.example.com:443'
      tenantId: _devops
      authMode: basic
      basicAuth:
        username: observe
        password: ${TEMPO_PASSWORD}
  metrics:
    enabled: true
    scrapeInterval: 60s
    node-exporter:
      enabled: true
    kube-state-metrics:
      enabled: true
    kubelet:
      enabled: true
    cadvisor:
      enabled: true
  logs:
    enabled: true
    pod_logs:
      enabled: true
  traces:
    enabled: true